export const GET_CONSTRUCTOR_DATA_SUCCESS = "GET_CONSTRUCTOR_DATA_SUCCESS";
export const GET_CONSTRUCTOR_DATA_ERROR = "GET_CONSTRUCTOR_DATA_ERROR";
export const GET_CONSTRUCTOR_DATA_REQUEST = "GET_CONSTRUCTOR_DATA_REQUEST";
export const ADD_CONSTRUCTOR_ELEMENT = "ADD_CONSTRUCTOR_ELEMENT";
export const REMOVE_CONSTRUCTOR_ELEMENT = "REMOVE_CONSTRUCTOR_ELEMENT";
export const SWAP_IN_CONSTRUCTOR = "SWAP_IN_CONSTRUCTOR";
export const CLEAR_CONSTRUCTOR = "CLEAR_CONSTRUCTOR";
