export const INIT_ORDERS_SOCKET = "INIT_ORDERS_SOCKET";
export const INIT_USER_ORDERS_SOCKET = "INIT_USER_ORDERS_SOCKET";
export const SUCCESS_ORDERS_SOCKET = "SUCCESS_ORDERS_SOCKET";
export const SUCCESS_USER_ORDERS_SOCKET = "SUCCESS_USER_ORDERS_SOCKET";
export const CLOSE_ORDERS_SOCKET = "CLOSE_ORDERS_SOCKET";
export const CLOSE_USER_ORDERS_SOCKET = "CLOSE_USER_ORDERS_SOCKET";
export const SET_ORDERS_DATA = "SET_ORDERS_DATA";
export const SET_USER_ORDERS_DATA = "SET_USER_ORDERS_DATA";
